stages:
  - test
  - build

image: tdba/simapi:sbcl_2.1.9

before_script:
  - git clone https://github.com/jeosol/hello-world.git ~/quicklisp/local-projects/hello-world

test:
 stage: test
 script:
   - make test

build:
 stage: build
 #only:
 #  - tags
 script:
   - make build
   - mv ~/quicklisp/local-projects/hello-world/bin ${CI_PROJECT_DIR}
   
 artifacts:
 paths:
   - bin
          
