# set the base image
FROM tdba/simapi:sbcl_2.1.9 as base-image

# clone the repository
# RUN git clone https://github.com/jeosol/hello-world.git /root/quicklisp/local-projects/hello-world

# copy the source code: need to specify the destination directory explicitly
COPY hello-world /root/quicklisp/local-projects/hello-world

WORKDIR /root/quicklisp/local-projects/hello-world/

COPY create-hello-world-exe.lisp .
COPY create-hello-world-exe.sh .

RUN chmod +x ./create-hello-world-exe.sh

# create the exe hello-world in the ./bin/ folder
RUN ./create-hello-world-exe.sh

WORKDIR /root/quicklisp/local-projects/hello-world

# set the startup script when we run the container
ENTRYPOINT ["./start-hello-world-exe.sh"]

